services: 
  db: 
    image: 'postgres:latest'
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${COURSE_DATABASE_USER}
      POSTGRES_DB: ${COURSE_DATABASE_NAME}
      POSTGRES_PASSWORD: ${COURSE_DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: 'local'