services: 
  db: 
    image: 'postgres:latest'
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${COURSE_DATABASE_USER}
      POSTGRES_DB: ${COURSE_DATABASE_NAME}
      POSTGRES_PASSWORD: ${COURSE_DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    ports:
      - 8081:80
    volumes: 
      - pgadmin:/var/lib/pgadmin
  app: 
    build: .
    ports:
      - 8080:8080
    environment:
      COURSE_DATABASE_NAME: ${COURSE_DATABASE_NAME}
      COURSE_DATABASE_USER: ${COURSE_DATABASE_USER}
      COURSE_DATABASE_PASSWORD: ${COURSE_DATABASE_PASSWORD}
      COURSE_DATABASE_PORT: ${COURSE_DATABASE_PORT:-5432}
      COURSE_DATABASE_HOST: ${COURSE_DATABASE_HOST_DOCKER:-db}
    depends_on:
      - db

volumes:
  db:
    driver: 'local'
  pgadmin:
    driver: 'local'